### PR TITLE
SQL Ledger Sprachpaket / locales.pl für neuere Perlversionen / Kontenrahmen

### PR DESCRIPTION
**Pull request by tapwag**
Hallo Rolf,

ich habe gestern Dieter eine Mail geschrieben und ihm über die Problematik mit dem locales.pl Skript gesprochen. Bei ihm läuft es wohl aber ich selbst habe eine "bleeding edge" openSUSE Tumbleweed-Installation mit dem neuesten Perl (5 Update 22). 

Dieter hat mir jedenfalls gesagt, was zu beheben ist und ich konnte nun auch ein all-file erzeugen. 

Weiterhin beinhaltet diese Pull request meine Übersetzung des Kontenrahmens der US Service Company. Ich habe erstmal auf Umlaute aus Kompatibilitätsgründen verzichtet. Der Kontenrahmen wird installiert, jedoch werde ich nach der Installation des Kontenrahmens über die admin.pl nicht weiter geleitet.

Feel free to merge.

Happy hacking,

Maik

### CODE REVIEW

**Comment by Tekki** [comment]
- language in this repo is English
- if you want to generat the "all" file, take locales.pl from locale/chd_utf
- did you realize that your own translation is de2_utf and not de_utf?
- to use umlauts, add a "Set client_endoding" command as in sql-ledger/sql/German-Sample-chart.sql
- if your coa doesn't install correctly, please wait with a pull request until it works

Tekki

**Comment by tapwag** [comment]
Okay, let's discuss in English, fine with me. 

As you can see from the changes I contributed I made the changes in de_utf and not de2_utf as I am not using this directory in my installation and do not understand why you created this in the first place. 

I made the changes to the de_utf directory. If you don't like the changes that I made then just don't merge this. That's fine with me but don't expect everyone to know on top of their heads to know what the de2_utf directory is for. 

In one email you sent to me (yes, I do read them) you claimed that Dieter broke the locales.pl script but as already mentioned he has been using an older Perl version and couldn't reproduce this. He supplied me with a fix to have this working on newer Perl versions and generating the all file worked fine then.

I will add the "Set client_encoding" later on. Thanks for this.

Feel free to add what you like and leave out what you don't like. It's as simple as that.

Have a nice day,

Maik

**Comment by Tekki** [comment]
I can't accept changes to the DWS translations because, as I've explained before, they will result in merge conflicts as soon as we get an update from Dieter.
You set the encoding of the coa to Latin-1, but the content is UTF-8.

**Comment by tapwag** [comment]
Thanks for the info concerning the encoding of the COA. I set the client encoding to UTF-8 and pushed it back into my repository.

**Comment by Tekki** [comment]
sql/German_Service-Company-chart.sql:
INSERT INTO defaults (fldname, fldvalue) VALUES ('income_accno_id', (SELECT id FROM chart WHERE accno = '4010'));

There is no account with number 4010 in the chart.
Besides that, you still write 'ue' instead of 'ü' at different places.

**Comment by tapwag** [comment]
I only had a brief look at the Umlaute-stuff yesterday but will now take a closer look. I am on it.

**Comment by tapwag** [comment]
Just a quick note on how this COA came to pass: I am using the US Service Company COA for my own small business and just took the SQL Code and translated some strings using a text editor. I am not that much of an expert when it comes to encoding (thanks for the slides, by the way). 

I noticed that there was client-side ISO encoding written in the SQL statements beforehand and therefore I didn't want to make things to complicated and rejected using Umlaute for the time being even though it does look amateurish. 

I understand that you opened up a company recently and that you are pretty busy with that. Just two questions:

Do you think it would be safe to drop the line with the INSERT statement you indicated? I can certainly do that.

Also I can't make much sense of the term "merging conflicts" - does this relate to github.com? 

I will also have a closer look at the locales.pl in the chd_utf directory. I am assuming this is Swiss-German which is quite different to the "Hochdeutsch" in my Lower-Saxony are.

Regards,


Maik

**Comment by tapwag** [comment]
I can across a merging conflict myself in the meantime. No further elaboration on that is necessary.

**Comment by Tekki** [comment]
No, you can't drop the INSERT statement, it sets a default account that is required for the program to work. Btw, the error is already in sql/US_Service_Company-chart.sql.
My translation is not Swiss German, which doesn't exist as a written language, but de_CH. It reflects the differences in the commercial vocabulary between Switzerland and Germany, and in many other places uses the technical terms of SAP.

I suggest that you close this pull request and open a new one with just a single commit when your coa is finished, and a second one when you have updated your translation.

**Comment by tapwag** [comment]
Thanks for the info. I remember that there is a Swiss accounting term "Treuhänder" and Switzerland definetely has its own style of doing business so that makes a lot of sense. I agree with your suggestion of closing the pull request which in fact has been the first one I ever issued on github.com.

**Pull request closed without merging**
